name: Cypress Qazando Tests
on:
  pull_request:
    branches: [master]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do projeto
      uses: actions/checkout@v4
    - name: Cypress run test
      uses: cypress-io/github-action@v6